apiVersion: v1
kind: Pod
metadata:
  name: cliente
  namespace: default  # Especifica el mismo namespace que el servicio y el StatefulSet
spec:
  restartPolicy: Never
  containers:
    - name: cliente
      image: localhost:5001/cliente:latest
      command:
        - sleep
        - "infinity"
      ports:
        - containerPort: 6001
      env:
        - name: MISUBDOMINIODNS
          value: ss-service.default.svc.cluster.local  # Apunta al servicio headless
