#
# Parece que los nombres del campo "containers" de pods a dar de alta en dns
# deben coincidir el subcampo campo "name" (servidor) del manifiesto con el nombre
# del contenedor en el registro (localhost:5001/servidor:latest)apiVersion: v1
kind: Service
metadata:
  name: ss-service
  labels:
    app: rep
spec:
  clusterIP: None   # Headless service, solo para dar de alta pods en DNS
  selector:      # tiene que coincidir con label definido en pod de StatefulSet
    app: rep  # Para dar de alta automaticamente en DNS a los PODS ligados
  ports:
  - port: 6000
    name: servidor-port
    protocol: TCP
    targetPort: 6000

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ss
spec:
  serviceName: ss-service
  replicas: 3
  podManagementPolicy: Parallel   # por defecto seria OrderedReady (secuencial)
  selector:
    matchLabels:
      app: rep    # tiene que corresponder a .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: rep
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: servidor
        image: localhost:5001/servidor:latest
        env:
        - name: MISUBDOMINIODNS
          value: ss-service.default.svc.cluster.local
        - name: MINOMBREPOD		# primera replica ss-0, segunda ss-1, etc
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
        - /servidor
        - $(MINOMBREPOD).$(MISUBDOMINIODNS):6000
        ports:
        - containerPort: 6000


