# Service
apiVersion: v1
kind: Service
metadata:
  name: ss-service
  labels:
    app: rep
spec:
  clusterIP: None   # Headless service, solo para dar de alta pods en DNS
  selector:
    app: rep
  ports:
  - port: 6000             # Comunicación interna entre pods
    targetPort: 6000
    name: interno
    protocol: TCP
  - port: 6001             # Test de carga externo
    targetPort: 6001
    name: carga
    protocol: TCP

---
# StatefulSet
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ss
spec:
  serviceName: ss-service
  replicas: 3
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: rep
  template:
    metadata:
      labels:
        app: rep
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: servidor
        image: localhost:5001/servidor:latest
        env:
        - name: MISUBDOMINIODNS
          value: ss-service.default.svc.cluster.local
        - name: MINOMBREPOD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
          - /bin/sh
          - -c
          - "/usr/sbin/sshd -D & /servidor $(MINOMBREPOD).$(MISUBDOMINIODNS):6000 1 ss-0.ss-service.default.svc.cluster.local:6000 ss-1.ss-service.default.svc.cluster.local:6000 ss-2.ss-service.default.svc.cluster.local:6000"

        ports:
        - containerPort: 6000   # Puerto para comunicación interna
          name: interno
        - containerPort: 6001   # Puerto para peticiones de test de carga
          name: carga


